services:
  db:
    image: postgres:latest
    container_name: pm_db
    environment:
      POSTGRES_DB: password-db
      POSTGRES_USER: password
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - password-manager-net

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    container_name: pm_api
    stdin_open: true
    tty: true
    ports:
      - "1234:8080"
    environment:
      DATABASE_URL: postgres://password:password123@pm_db/password-db
    depends_on:
      - db
    networks:
      - password-manager-net

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pm_app
    stdin_open: true
    tty: true
    ports:
      - "4000:80"
    depends_on:
      - api

volumes:
  db:

networks:
  password-manager-net:
    name: password-manager-net
    driver: bridge
