services:
  db:
    image: postgres:latest
    container_name: pm_db
    environment:
      POSTGRES_DB: password-db
      POSTGRES_USER: password
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - password-manager-net

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    container_name: pm_api
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://password:password123@pm_db/password-db
    depends_on:
      - db
    networks:
      - password-manager-net
      - nginx-proxy-net

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pm_app
    stdin_open: true
    tty: true
    environment:
      API_URL: 'apipm.rayan.lol/api'
    depends_on:
      - api
    networks:
      - nginx-proxy-net

volumes:
  db:

networks:
  nginx-proxy-net:
    external:
      name: nginx-proxy-net
  password-manager-net:
    driver: bridge
